# Generated by Django 4.1.7 on 2023-03-31 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('drivers_license', models.CharField(max_length=50)),
                ('identification_card', models.CharField(max_length=50, unique=True)),
                ('model_vehicle', models.CharField(max_length=50)),
                ('car_license_plate', models.CharField(max_length=50, unique=True)),
                ('soat', models.CharField(max_length=50)),
                ('driver_approved', models.BooleanField(null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('driver_active', models.BooleanField(null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('reference_point', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
