# Generated by Django 4.1.7 on 2023-03-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_active',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
