# Generated by Django 4.1.7 on 2023-03-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0002_alter_driver_driver_active_alter_driver_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='latitude',
            field=models.FloatField(default=0),
        ),
    ]
