# Generated by Django 4.1.7 on 2023-04-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
