# Generated by Django 4.1.7 on 2023-04-01 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Driver', '0003_alter_driver_driver_active_alter_driver_latitude'),
        ('Rider', '0002_alter_rider_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requet_active', models.BooleanField(null=True)),
                ('requet_finalized', models.BooleanField(null=True)),
                ('ponit_start', models.CharField(max_length=50, null=True)),
                ('ponit_finish', models.CharField(max_length=50, null=True)),
                ('time_travel', models.FloatField(null=True)),
                ('id_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Driver.driver')),
                ('id_rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rider.rider')),
            ],
        ),
    ]
