# Generated by Django 4.1.7 on 2023-04-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='time_travel',
            field=models.FloatField(default=0, null=True),
        ),
    ]
