# Generated by Django 4.1.7 on 2023-04-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0003_alter_request_id_driver_alter_request_id_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='distance_travel',
            field=models.FloatField(default=0, null=True),
        ),
    ]
