# Generated by Django 4.1.7 on 2023-04-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0005_alter_request_id_driver_alter_request_id_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
