# Generated by Django 4.1.7 on 2023-04-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0006_request_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='cost',
            field=models.FloatField(default=0, null=True),
        ),
    ]
